#!/bin/sh

set -e

VARIANT="diot-tester-fastino"


artiq_compile --device-db build/$VARIANT/device_db.py -o build/$VARIANT/startup.elf experiments/startup.py
artiq_compile --device-db build/$VARIANT/device_db.py -o build/$VARIANT/idle.elf experiments/fastino_square.py

artiq_mkfs -s ip 192.168.95.70 \
    -f idle_kernel build/$VARIANT/idle.elf \
    -f startup_kernel build/$VARIANT/startup.elf \
    build/$VARIANT/storage.img 
