#!/bin/sh

VARIANT="diot-tester-fastino"

artiq_flash -t kasli_diot --srcbuild -d build/$VARIANT \
    -f build/$VARIANT/storage.img \
    erase=firmware,bootloader,gateware,storage \
    write=firmware,bootloader,storage load
