line-length = 88
indent-width = 4
target-version = "py311"

[lint]
extend-select = ["B", "A", "SIM", "TID", "PTH", "UP", "RUF", "ANN"]
ignore = ["UP012", "RUF012", "RUF010", "PTH123", "ANN201", "ANN202"]